### PR TITLE
ChaelCodes greetings

### PR DESCRIPTION
**Pull request by surlydev**
redone ChaelCodes SuperVIP greetings

### CODE REVIEW

**Comment by MillerMark** [comment]
"hope you are sat"?

**Comment by surlydev** [comment]
sat? as in sitting. Sitting with her feet up snuggling the cats.

**Comment by surlydev** [comment]
do you mean that it should say "I hope you are sitting ..." ?

**Comment by MillerMark** [comment]
Thanks Surly. Yes, that is what I meant. Merged.

**Pull request merged**
