### PR TITLE
Greetings (Earthling). Additional generic, and VIP greetings.

### PR DESCRIPTION
**Pull request by surlydev**
New generic greetings, and New VIP greetings for sxPositive, JTsom, CodebaseAlpha, BaldBeardedBuilder, TehPudding, CopperBeardy and Phrakberg

### CODE REVIEW

**Comment by surlydev** [comment]
Added in a greeting for ChaelCodes.

**Review by surlydev — COMMENTED** [review]
@MillerMark if you merge this PR I can do another one right after it where I re-order the functions in alphabetical order? It was kinda bugging me that the names weren't alphabetical.

**Comment by surlydev** [comment]
Added another edit to the VIPGreeting for ChaelCodes, to see if Mr A can paste clip links

**Comment by MillerMark** [comment]
Manually integrated/merged these changes into the master branch (with a few minor edits). Thanks Surly!

**Comment by surlydev** [comment]
Am I right in assuming you haven't pushed that file up to the Master branch yet @MillerMark ?

**Comment by MillerMark** [comment]
Just pushed it after seeing this.

**Comment by surlydev** [comment]
Some funny additions in there. Shame the ChaelCodes ones didn't make it in from the later commit.

I like the separate branch for BBB's on Tuesday's.

**Pull request closed without merging**
